source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FlourishUI_Example' do
  pod "FlourishUI", :path => "../"
end

target 'FlourishUI_Tests' do
  pod "FlourishUI", :path => "../"
end
